server:
  port:8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=from, open-api
      routes:
        - id: caixy-api-gateway
          uri: http://localhost:12300
          predicates:
            - Path=/api/**


dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:12300