spring:
#  profiles:
#    active: dev
  application:
    name: openApiPlatformBackend


  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_db
    username: root
    password: as123456789
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 192.168.59.226
    database: 0
  mail:
    host: smtp.163.com
    username: this_is_syuyangowo@163.com
    password: YOUR_PASSWORD
    defaultEncoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          stattls:
            require: true
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

encryption:
  key: CAIXYRPOMISE



dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

redis-session:
  instances:
    limiter:
      database: 1
      host: 192.168.59.226
      port: 6379

logging:
  level:
    org.springframework.boot: DEBUG

thread-pool:
  instances:
    default:
      corePoolSize: 2
      maxPoolSize: 4
      queueCapacity: 30
      keepAliveSeconds: 120
      timeUnit: SECONDS
alipay:
  appId: your_app_id
  appPrivateKey: your_app_private_key
  alipayPublicKey: YOUR_ALIPAY_PUBLIC_KEY
  notifyUrl: your_notify_url
  isSandbox: true