server:
  port:8080

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, caixy-api-gateway
      routes:
        - id: caixy-api-gateway
        - uri: http://localhost:8081
          predicates:
            - Path=/api/**